# Generated by Django 3.0.5 on 2020-04-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Menu'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='item',
            field=models.CharField(max_length=64),
        ),
    ]
