# Generated by Django 3.0.5 on 2020-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='pizza.Topping'),
        ),
    ]
