# Generated by Django 3.0.5 on 2020-04-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20200423_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pizza.Type'),
        ),
    ]
